server:
  port: 9088

# 指定mybatis信息
mybatis:
  config-location: classpath:mybatis-config.xml

# 打印sql
spring:
  shardingsphere:
    props:
      sql:
        show: true

    datasource:
      names: ds0, ds1

    ds0:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ds0?characterEncoding=utf-8
      username: root
      password: root

    ds1:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ds1?characterEncoding=utf-8
      username: root
      password: root

    sharding:
      default-database-strategy:
        inline:
          sharding-column: age
          algorithm-expression: ds$->{age % 2}

      tables:
        tab_user:
          actual-data-nodes: ds$->{0..1}.tab_user$->{0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: tab_user$->{id % 2}
